services:
  app:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./skeleton/.env
    volumes:
      - ./skeleton:/var/www/html
    ports:
      - 9000:9000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./skeleton:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:

volumes:
  db_data: