services:
  php:
    image: php:8.4-fpm
    build: 
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    volumes:
      - ../symfony/skeleton:/var/www/html
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../symfony/skeleton:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symf-docker
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony: